[general]
import = [
  "~/.config/alacritty/themes/noctalia.toml"
]

[terminal]
shell =  { program = "/bin/fish", args = ["-l"] }
osc52 =  "CopyPaste"

[font]
size = 10.0
normal = { family = "RobotoMono Nerd Font Mono" }
# normal = { family = "FiraCode Nerd Font Mono" }

[window]
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "Both"

[scrolling]
history = 3023

[cursor]
style = { shape = "Underline", blinking = "On" }
thickness = 0.2
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_interval = 500
unfocused_hollow = true

[mouse]
hide_when_typing = true

[bell]
duration = 0

[keyboard]
bindings = [
  { key = "C",       mods = "Control|Shift", action = "Copy"  },
  { key = "V",       mods = "Control|Shift", action = "Paste" },
  { key = "N",       mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "Equals",  mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "Minus",   mods = "Control",       action = "DecreaseFontSize" },
  { key = "Key0",    mods = "Control",       action = "ResetFontSize"    },
  { key = "Enter",   mods = "Shift",         chars = "\n" },
]
