[colors.primary]
background = '#1a1110'
foreground = '#f1dfdb'

[colors.selection]
text = '#f1dfdb'
background = '#73342a'

[colors.cursor]
text = '#1a1110'
cursor = '#ffb4a7'

[colors.normal]
black   = '#1a1110'
red     = '#e14984'
green   = '#9bd66e'
yellow  = '#dbaa7b'
blue    = '#c86654'
magenta = '#bf928a'
cyan    = '#ffb4a7'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f94'
green   = '#ade086'
yellow  = '#e8be97'
blue    = '#ffc0b3'
magenta = '#bc5c5d'
cyan    = '#a26c58'
white   = '#ffffff'

[colors.normal]
black   = '#1e100d'
red     = '#e14984'
green   = '#9bd66e'
yellow  = '#dbaa7b'
blue    = '#c86654'
magenta = '#bf928a'
cyan    = '#ffb4a7'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f94'
green   = '#ade086'
yellow  = '#e8be97'
blue    = '#ffc0b3'
magenta = '#bc5c5d'
cyan    = '#a26c58'
white   = '#ffffff'

[colors.normal]
black   = '#181211'
red     = '#e14984'
green   = '#9bd66e'
yellow  = '#dbaa7b'
blue    = '#c86654'
magenta = '#bf928a'
cyan    = '#ffb4a7'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f94'
green   = '#ade086'
yellow  = '#e8be97'
blue    = '#ffc0b3'
magenta = '#bc5c5d'
cyan    = '#a26c58'
white   = '#ffffff'

[colors.normal]
black   = '#181211'
red     = '#e14984'
green   = '#9bd66e'
yellow  = '#dbaa7b'
blue    = '#c86654'
magenta = '#bf928a'
cyan    = '#ffb4a7'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f94'
green   = '#ade086'
yellow  = '#e8be97'
blue    = '#ffc0b3'
magenta = '#bc5c5d'
cyan    = '#a26c58'
white   = '#ffffff'
