format = "$all$time$cmd_duration$line_break$character"
continuation_prompt = 'â–¶â–¶ '

[time]
format = 'at [ğŸ•™ $time]($style) '
disabled = false

[directory]
format = '[ğŸ“‚ $path]($style)[$read_only]($read_only_style) '
truncation_symbol = '.../'
truncation_length = 8

[character]
error_symbol = '[âœ—](bold red) '
success_symbol = '[âœ](bold green) '

[git_branch]
symbol = 'ï˜ '
